Add Travis CI mypy

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -34,13 +34,17 @@ install:
                 pip install flake8-docstrings;
                 pip install pydocstyle==3.0.0;
                 pip install python-coveralls;
+                pip install mypy==0.540;
                 flake8 --version;
+                mypy --version;
             else
                 pip install flake8;
                 pip install flake8-docstrings;
                 pip install pydocstyle;
                 pip install python-coveralls;
+                pip install mypy;
                 flake8 --version;
+                mypy --version;
             fi
       fi
     - sh travis.sh bootstrap
@@ -50,6 +54,13 @@ script:
     - sh travis.sh run_syntax_tests
     - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
             flake8;
+            if [ "$TRAVIS_PYTHON_VERSION" == "3.3" ]; then
+                # Allow failures for mypy on older version of python.
+                mypy ../NeoVintageous || true;
+            else
+                # Temporarily allow failures for mypy.
+                mypy --show-error-codes ../NeoVintageous || true;
+            fi
       fi
 
 after_success:
